// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: blockchain.proto
#ifndef GRPC_blockchain_2eproto__INCLUDED
#define GRPC_blockchain_2eproto__INCLUDED

#include "blockchain.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace blockchain {

class Blockchain final {
 public:
  static constexpr char const* service_full_name() {
    return "blockchain.Blockchain";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::blockchain::TransactionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::blockchain::TransactionResponse>> AsyncTransaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::blockchain::TransactionResponse>>(AsyncTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::blockchain::TransactionResponse>> PrepareAsyncTransaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::blockchain::TransactionResponse>>(PrepareAsyncTransactionRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::blockchain::TransactionResponse>* AsyncTransactionRaw(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::blockchain::TransactionResponse>* PrepareAsyncTransactionRaw(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::blockchain::TransactionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>> AsyncTransaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>>(AsyncTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>> PrepareAsyncTransaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>>(PrepareAsyncTransactionRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, std::function<void(::grpc::Status)>) override;
      void Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>* AsyncTransactionRaw(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>* PrepareAsyncTransactionRaw(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Transaction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Transaction(::grpc::ServerContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Transaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Transaction() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Transaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transaction(::grpc::ServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransaction(::grpc::ServerContext* context, ::blockchain::TransactionRequest* request, ::grpc::ServerAsyncResponseWriter< ::blockchain::TransactionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Transaction<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Transaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Transaction() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::blockchain::TransactionRequest, ::blockchain::TransactionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response) { return this->Transaction(context, request, response); }));}
    void SetMessageAllocatorFor_Transaction(
        ::grpc::experimental::MessageAllocator< ::blockchain::TransactionRequest, ::blockchain::TransactionResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::blockchain::TransactionRequest, ::blockchain::TransactionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Transaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transaction(::grpc::ServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Transaction(
      ::grpc::CallbackServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Transaction(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Transaction<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Transaction<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Transaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Transaction() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Transaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transaction(::grpc::ServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Transaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Transaction() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Transaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transaction(::grpc::ServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransaction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Transaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Transaction() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Transaction(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Transaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transaction(::grpc::ServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Transaction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Transaction(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Transaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Transaction() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::blockchain::TransactionRequest, ::blockchain::TransactionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::blockchain::TransactionRequest, ::blockchain::TransactionResponse>* streamer) {
                       return this->StreamedTransaction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Transaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Transaction(::grpc::ServerContext* /*context*/, const ::blockchain::TransactionRequest* /*request*/, ::blockchain::TransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTransaction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::blockchain::TransactionRequest,::blockchain::TransactionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Transaction<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Transaction<Service > StreamedService;
};

}  // namespace blockchain


#endif  // GRPC_blockchain_2eproto__INCLUDED
