// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: blockchain.proto

#include "blockchain.pb.h"
#include "blockchain.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace blockchain {

static const char* Blockchain_method_names[] = {
  "/blockchain.Blockchain/Transaction",
};

std::unique_ptr< Blockchain::Stub> Blockchain::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Blockchain::Stub> stub(new Blockchain::Stub(channel));
  return stub;
}

Blockchain::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Transaction_(Blockchain_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Blockchain::Stub::Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::blockchain::TransactionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Transaction_, context, request, response);
}

void Blockchain::Stub::experimental_async::Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Transaction_, context, request, response, std::move(f));
}

void Blockchain::Stub::experimental_async::Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Transaction_, context, request, response, std::move(f));
}

void Blockchain::Stub::experimental_async::Transaction(::grpc::ClientContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Transaction_, context, request, response, reactor);
}

void Blockchain::Stub::experimental_async::Transaction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::blockchain::TransactionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Transaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>* Blockchain::Stub::AsyncTransactionRaw(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::blockchain::TransactionResponse>::Create(channel_.get(), cq, rpcmethod_Transaction_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::blockchain::TransactionResponse>* Blockchain::Stub::PrepareAsyncTransactionRaw(::grpc::ClientContext* context, const ::blockchain::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::blockchain::TransactionResponse>::Create(channel_.get(), cq, rpcmethod_Transaction_, context, request, false);
}

Blockchain::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Blockchain_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Blockchain::Service, ::blockchain::TransactionRequest, ::blockchain::TransactionResponse>(
          [](Blockchain::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::blockchain::TransactionRequest* req,
             ::blockchain::TransactionResponse* resp) {
               return service->Transaction(ctx, req, resp);
             }, this)));
}

Blockchain::Service::~Service() {
}

::grpc::Status Blockchain::Service::Transaction(::grpc::ServerContext* context, const ::blockchain::TransactionRequest* request, ::blockchain::TransactionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace blockchain

